# Generated by Django 5.1.2 on 2025-01-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
